version: "3"

networks:
  mongodb:
    external: true

services:
  external_api:
    image: fake2truth-external_api:0.1.0
    build:
      dockerfile: Dockerfile.external_api
    ports:
      - "8080:8080"
    networks:
      - mongodb
    volumes:
      - "./config.yaml:/app/config.yaml"
    environment:
    - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    stop_grace_period: 1s